version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: notion-clone-backend-prod
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - NODE_ENV=production
    volumes:
      - ./backend/data:/app/data
    restart: always
    command: ./main

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: notion-clone-frontend-prod
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:4000
    restart: always
    depends_on:
      - backend
    command: npm start 