version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notion-clone-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - COOKIE_SECRET=your_cookie_secret_key_change_in_production
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/data:/app/data
    restart: unless-stopped
    command: npm run dev

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notion-clone-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    depends_on:
      - backend
    command: npm run dev 